---
# tasks file for ansible-role-nfs_server_openbsd

- name: Enable portmap
  service:
    name: portmap
    arguments: "{{ nfs_server_openbsd_portmap_flags }}"
    enabled: yes
  notify:
    - Restart portmap

- name: Enable mountd
  service:
    name: mountd
    arguments: "{{ nfs_server_openbsd_mountd_flags }}"
    enabled: yes
  notify:
    - Reload mountd

- name: Enable nfsd
  service:
    name: nfsd
    arguments: "{{ nfs_server_openbsd_nfsd_flags }}"
    enabled: yes
  notify:
    - Restart nfsd

- name: Create exports(5)
  template:
    src: exports.j2
    dest: /etc/exports
  notify:
    - Reload mountd

- name: Start portmap, mountd, and nfsd
  service:
    name: "{{ item }}"
    state: started
  with_items:
    - portmap
    - mountd
    - nfsd
